### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by bmuenzenmeyer** [SignetStudios/rainwave-client#6]
On a clean clone of this repo, I attempt to Build:

OS `Windows 10 Pro`
Bitness `64bit`
.NET `4.6.1`

![image](https://cloud.githubusercontent.com/assets/298435/26784164/b4d909d8-49c1-11e7-8a6d-3de94e093196.png)

**Comment by kingofzeal** [comment]
Please make sure you have the Windows SDK installed. You can find it at https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

There may also be in option to install the Windows SDK when installing/upgrading Visual Studio 2017, but cannot confirm that at this time.

If you still have issues building after installing the SDK, we'll reopen the issue and I'll look into it further.
